// GENERATED by tools/gen_shaders.dart from shaders/*.vert,frag — do not edit.




const String worldVertSrc = '''
#version 300 es
layout(location=0) in vec3 aPos;
layout(location=1) in vec4 aColor;
layout(location=2) in float aAlpha;
layout(location=3) in vec3 aNormal;
layout(location=4) in vec3 aUv;
// Instance attributes for model matrix (instancing support)
layout(location=5) in vec4 aModelRow0;
layout(location=6) in vec4 aModelRow1;
layout(location=7) in vec4 aModelRow2;
layout(location=8) in vec4 aModelRow3;
layout(location=9) in vec4 aMaterialTint;
uniform vec3 uEye,uFwd,uUp,uRight,uLight,uLightColor;
uniform float uScale,uAspect,uDepthNear,uDepthFar,uAmbient,uDiffuse;
uniform float uAffineTexture;
uniform vec2 uInternal;
uniform mat4 uModel;
uniform bool uInstanced;
uniform mat4 uLightProj0,uLightProj1,uLightProj2;
uniform int uPointLightCount;
uniform vec3 uPointLightPos[4],uPointLightColor[4];
uniform float uPointLightRadius[4],uPointLightIntensity[4];
out float vDepth;
out vec4 vColor;
out float vAlpha;
out vec3 vNormal;
out highp vec3 vUv;
out float vW;
out vec3 vLight;
out vec3 vWorldPos;
out vec4 vShadowCoord[3];
out vec4 vMaterialTint;
void main(){
  mat4 model = uInstanced ? mat4(aModelRow0, aModelRow1, aModelRow2, aModelRow3) : uModel;

  vec3 worldPos=vec3(model*vec4(aPos,1.0));
  vec3 p=worldPos-uEye;
  vec3 worldNormal=normalize(vec3(model*vec4(aNormal,0.0)));
  float depth=dot(p,uFwd);
  float z=(depth-uDepthNear)/(uDepthFar-uDepthNear)*2.0-1.0;
  gl_Position=vec4(dot(p,uRight)*uScale*uAspect,dot(p,uUp)*uScale,z*depth,depth);
  if(uInternal.x>0.0){
    vec2 g=uInternal;
    gl_Position.xy=floor(gl_Position.xy/gl_Position.w*g+0.5)/g*gl_Position.w;
  }
  vDepth=depth;
  vColor=aColor;
  vAlpha=aAlpha;
  vNormal=worldNormal;
  vUv=mix(aUv,aUv*gl_Position.w,uAffineTexture);
  vW=mix(1.0,gl_Position.w,uAffineTexture);
  vWorldPos=worldPos;
  vMaterialTint=uInstanced?aMaterialTint:vec4(0.0,1.0,1.0,1.0);
  vShadowCoord[0]=uLightProj0*vec4(worldPos,1.0);
  vShadowCoord[1]=uLightProj1*vec4(worldPos,1.0);
  vShadowCoord[2]=uLightProj2*vec4(worldPos,1.0);
  float ndl=max(0.0,dot(worldNormal,uLight));
  vLight=vec3(uAmbient)+uLightColor*(uDiffuse*ndl);
  for(int i=0;i<4;i++){
    if(i>=uPointLightCount)break;
    vec3 toLight=uPointLightPos[i]-worldPos;
    float distanceToLight=length(toLight);
    if(distanceToLight>0.0001&&distanceToLight<uPointLightRadius[i]){
      float pointNdl=max(0.0,dot(worldNormal,toLight/distanceToLight));
      float falloff=smoothstep(uPointLightRadius[i],0.0,distanceToLight);
      vLight+=uPointLightColor[i]*(uPointLightIntensity[i]*pointNdl*falloff*falloff);
    }
  }
}
''';

const String worldFragSrc = '''
#version 300 es
precision mediump float;
precision mediump sampler2DArray;
in float vDepth;
in vec4 vColor;
in float vAlpha;
in vec3 vNormal;
in highp vec3 vUv;
in float vW;
in vec3 vLight;
in vec3 vWorldPos;
in vec4 vShadowCoord[3];
in vec4 vMaterialTint;
uniform vec3 uFog;
uniform sampler2D uWall,uGlass,uSoft,uNoise;
uniform sampler2DArray uMaterialAlbedo;
uniform sampler2D uShadow0,uShadow1,uShadow2;
uniform float uFogStart,uFogEnd,uFlicker,uBloomThreshold;
uniform float uFogDensity,uFogHeightFalloff,uFogGroundHeight;
uniform float uRainIntensity,uSurfaceWetness,uWindowWetness;
uniform float uColorQuantize;
uniform float uWallOn,uWallMid,uWallAmt,uWallScale,uGlassOn,uGlassGain,uGlassFog,uSoftOn,uNoiseOn;
uniform float uShadowCasters;
uniform vec3 uShadowBias;
uniform bool uInstanced;
uniform int uMaterialCount;
uniform int uStaticMaterial;
uniform float uMaterialEmissive[32];
uniform float uMaterialUvScale[32];
uniform int uMaterialLayer[32];
uniform int uMaterialFlags[32];
layout(location=0) out vec4 oColor;
layout(location=1) out vec4 oGlow;
vec3 quantizeColor(vec3 c){
  if(uColorQuantize<0.5)return clamp(c,0.0,1.0);
  float n=0.0;
  if(uNoiseOn>0.0){
    n=(texture(uNoise,(gl_FragCoord.xy/64.0)).r-0.5)*0.04;
  }
  vec3 q=round((c*31.0+n*31.0))/31.0;
  return clamp(q,0.0,1.0);
}
struct MaterialProps{
  float emissive;
  float uvScale;
  int layer;
  int flags;
};
MaterialProps getMaterialProps(int idx){
  MaterialProps p;
  if(idx>=0&&idx<uMaterialCount){
    p.emissive=uMaterialEmissive[idx];
    p.uvScale=uMaterialUvScale[idx];
    p.layer=uMaterialLayer[idx];
    p.flags=uMaterialFlags[idx];
  }else{
    p.emissive=0.0;
    p.uvScale=1.0;
    p.layer=0;
    p.flags=0;
  }
  return p;
}
float sampleShadow(sampler2D shadowTex,vec4 shadowCoord,vec3 normal){
  vec3 projCoords=shadowCoord.xyz/shadowCoord.w;
  projCoords=projCoords*0.5+0.5;
  if(projCoords.z>1.0||projCoords.x<0.0||projCoords.x>1.0||projCoords.y<0.0||projCoords.y>1.0)return 1.0;
  float currentDepth=projCoords.z;
  float bias=max(uShadowBias.x, uShadowBias.y*abs(dFdy(currentDepth)));
  vec2 texelSize=vec2(1.0/512.0);
  float shadowSum=0.0;
  for(int x=-1;x<=1;x++){
    for(int y=-1;y<=1;y++){
      float pcfDepth=texture(shadowTex,projCoords.xy+vec2(x,y)*texelSize).r;
      shadowSum+=(currentDepth-bias>pcfDepth)?0.15:1.0;
    }
  }
  return shadowSum/9.0;
}
void main(){
  vec3 uv=vUv/vW;
  if(uv.z>1.5){
    float m=uSoftOn>0.0?texture(uSoft,uv.xy).r
                       :max(0.0,1.0-2.0*length(uv.xy-vec2(0.5)));
    if(uv.z>3.5){
      vec3 c=quantizeColor(vColor.rgb);
      oColor=vec4(c,m*vAlpha);
      oGlow=vec4(c*step(uBloomThreshold,vColor.a),m*vAlpha);
      return;
    }
    if(uv.z>2.5){
      vec3 c=quantizeColor(vColor.rgb);
      oColor=vec4(c*m*vAlpha,0.0);
      oGlow=vec4(0.0);
      return;
    }
  }
  float shadow=1.0;
  if(uShadowCasters>0.5)shadow=min(shadow,sampleShadow(uShadow0,vShadowCoord[0],vNormal));
  if(uShadowCasters>1.5)shadow=min(shadow,sampleShadow(uShadow1,vShadowCoord[1],vNormal));
  if(uShadowCasters>2.5)shadow=min(shadow,sampleShadow(uShadow2,vShadowCoord[2],vNormal));
  vec3 c=vColor.rgb*vLight*shadow;
  int materialIndex=uInstanced?int(vMaterialTint.x+0.5):uStaticMaterial;
  MaterialProps material=getMaterialProps(materialIndex);
  if(uInstanced){
    c*=vMaterialTint.yzw;
  }
  if(materialIndex>=0&&materialIndex<uMaterialCount){
    c*=texture(uMaterialAlbedo,vec3(uv.xy*material.uvScale,float(material.layer))).rgb;
  }
  float a=vAlpha;

  // Surface wetness PBR modification
  if (uSurfaceWetness > 0.001) {
    c *= mix(1.0, 0.65, uSurfaceWetness * 0.85);
  }

  // Calculate exponential height fog if density > 0, otherwise fallback to linear range
  float fog = 0.0;
  if (uFogDensity > 0.0001) {
    float heightDecay = exp(-uFogHeightFalloff * max(vWorldPos.y - uFogGroundHeight, 0.0));
    fog = clamp(1.0 - exp(-uFogDensity * vDepth * heightDecay), 0.0, 1.0);
  } else {
    fog = smoothstep(uFogStart, uFogEnd, vDepth);
  }

  if(uv.z>1.5){
    if(uGlassOn>0.0){
      vec2 glassUv = uv.xy;
      if (uWindowWetness > 0.05 && uNoiseOn > 0.0) {
        vec2 dropUv = uv.xy * 6.0 + vec2(0.0, -uv.y * 0.3);
        glassUv += (texture(uNoise, dropUv).rg - 0.5) * 0.03 * uWindowWetness;
      }
      vec4 g=texture(uGlass,glassUv);
      c=vColor.rgb*g.rgb*uGlassGain;
      a*=g.a;
      fog *= clamp(uGlassFog, 0.1, 1.0);
    }
  }else if(uv.z>0.5&&uWallOn>0.0){
    c*=1.0+(texture(uWall,uv.xy*uWallScale*material.uvScale).r-uWallMid)*uWallAmt;
  }
  c+=vColor.rgb*material.emissive;
  c=mix(c,uFog,fog);
  if(vColor.a>0.0) c*=1.0+vColor.a*uFlicker;
  c=quantizeColor(c);
  oColor=vec4(c,a);
  oGlow=vec4(c*step(uBloomThreshold,vColor.a),a);
}
''';

const String postVertSrc = '''
#version 300 es
out vec2 vUv;
void main(){
  vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));
  vUv=p;
  gl_Position=vec4(p*2.0-1.0,0.0,1.0);
}
''';

const String blurFragSrc = '''
#version 300 es
precision mediump float;
in vec2 vUv;
uniform sampler2D uTex;
uniform vec2 uDir;
out vec4 oColor;
void main(){
  float w[5]=float[](0.227,0.194,0.121,0.054,0.016);
  vec4 c=texture(uTex,vUv)*w[0];
  for(int i=1;i<5;i++){
    vec2 o=uDir*float(i);
    c+=texture(uTex,vUv+o)*w[i];
    c+=texture(uTex,vUv-o)*w[i];
  }
  oColor=c;
}
''';

const String postFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uTex,uBloom,uNoise,uLut,uDepth,uSSAO;
uniform vec2 uNoiseOff;
uniform float uTime,uFlash,uVignette,uGrain,uDesat,uBloomStrength,uBlur,uNoiseOn,uLutOn,uLutMix,uDepthViz,uSSAOStrength;
out vec4 oColor;
vec3 slice(float s,vec2 rg){
  return texture(uLut,vec2((s*16.0+rg.x*15.0+0.5)/256.0,(rg.y*15.0+0.5)/16.0)).rgb;
}
void main(){
  vec4 c=texture(uTex,vUv);
  if(uDepthViz>0.0){
    float d=texture(uDepth,vUv).r;
    c=vec4(vec3(d),1.0);
  }else if(uBlur>0.0){
    vec2 d=(vec2(0.5)-vUv)*uBlur;
    for(int i=1;i<6;i++) c+=texture(uTex,vUv+d*(float(i)/6.0));
    c/=6.0;
  }
  float v=1.0-uVignette*dot(vUv-0.5,vUv-0.5);
  c.rgb*=v;
  float lum=dot(c.rgb,vec3(0.299,0.587,0.114));
  c.rgb=mix(c.rgb,vec3(lum),uDesat*(1.0-lum));
  float g;
  if(uNoiseOn>0.0){
    g=texelFetch(uNoise,(ivec2(gl_FragCoord.xy)+ivec2(uNoiseOff))%64,0).r*2.0-1.0;
  }else{
    g=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233))+uTime)*43758.5453)*2.0-1.0;
  }
  c.rgb+=g*uGrain;
  c.rgb+=texture(uBloom,vUv).rgb*uBloomStrength;
  if(uLutOn>0.0){
    vec3 q=clamp(c.rgb,0.0,1.0);
    float b=q.b*15.0;
    float s0=floor(b);
    c.rgb=mix(c.rgb,mix(slice(s0,q.rg),slice(min(s0+1.0,15.0),q.rg),b-s0),uLutMix);
  }
  float ssao=texture(uSSAO,vUv).r;
  c.rgb*=mix(1.0,ssao,uSSAOStrength);
  if(uFlash>0.0){
    c.r=texture(uTex,vUv+vec2(0.004*uFlash,0.0)).r;
    c.b=texture(uTex,vUv-vec2(0.004*uFlash,0.0)).b;
    c.rgb*=1.0-0.5*uFlash;
  }
  oColor=c;
}
''';

const String shadowVertSrc = '''
#version 300 es
in vec3 aPos;
in vec3 aNormal;
uniform mat4 uLightProj;
uniform mat4 uModel;
out float vDepth;

void main(){
  vec3 worldPos=vec3(uModel*vec4(aPos,1.0));
  vec4 lightPos=uLightProj*vec4(worldPos,1.0);
  gl_Position=lightPos;
  vDepth=lightPos.z/lightPos.w;
}
''';

const String shadowFragSrc = '''
#version 300 es
precision highp float;
in float vDepth;

void main(){
  gl_FragDepth=vDepth*0.5+0.5;
}
''';

const String dofFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uTex, uDepth;
uniform float uFocusDistance, uDofBlurScale, uBlurRadius, uDofStrength;
uniform vec2 uTexel;
out vec4 oColor;

vec4 sampleBlur(vec2 uv, float radius) {
  if (radius < 0.01) return texture(uTex, uv);
  float w[5] = float[](0.227, 0.194, 0.121, 0.054, 0.016);
  vec4 c = texture(uTex, uv) * w[0];
  for (int i = 1; i < 5; i++) {
    vec2 o = uTexel * float(i) * radius;
    c += texture(uTex, uv + o) * w[i];
    c += texture(uTex, uv - o) * w[i];
  }
  return c;
}

void main() {
  float depth = texture(uDepth, vUv).r;
  float coc = abs(depth - uFocusDistance) * uDofBlurScale;
  coc = clamp(coc, 0.0, uBlurRadius);
  coc *= uDofStrength;
  oColor = sampleBlur(vUv, coc);
}
''';

const String vhsFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uTex;
uniform sampler2D uNoise;
uniform float uTime;
uniform vec2 uTexelSize;
uniform vec2 uNoiseOff;

uniform bool uChromaLuma;
uniform bool uChromaLag;
uniform bool uTapeNoise;
uniform bool uHeadSwitch;
uniform bool uTracking;
uniform bool uDropouts;
uniform bool uGhosting;

uniform float uChromaBlurI;
uniform float uChromaBlurQ;
uniform float uChromaLagAmount;
uniform float uNoiseScale;
uniform float uHeadSwitchHeight;
uniform float uHeadSwitchJitter;
uniform float uJitterAmount;
uniform float uJitterFreq;
uniform float uDropoutRate;
uniform float uGhostAmount;
uniform float uGhostOffset;

uniform sampler2D uGhostTarget;
uniform bool uHasGhost;

out vec4 oColor;

vec3 rgbToYiq(vec3 rgb) {
  return vec3(
    0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b,
    0.596 * rgb.r - 0.274 * rgb.g - 0.322 * rgb.b,
    0.211 * rgb.r - 0.523 * rgb.g + 0.312 * rgb.b
  );
}

vec3 yiqToRgb(vec3 yiq) {
  return vec3(
    yiq.r + 0.956 * yiq.g + 0.621 * yiq.b,
    yiq.r - 0.272 * yiq.g - 0.647 * yiq.b,
    yiq.r - 1.106 * yiq.g + 1.703 * yiq.b
  );
}

float hash(vec2 p) {
  return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

float smoothHash(vec2 p) {
  vec2 i = floor(p);
  vec2 f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  float a = hash(i);
  float b = hash(i + vec2(1.0, 0.0));
  float c = hash(i + vec2(0.0, 1.0));
  float d = hash(i + vec2(1.0, 1.0));
  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

void main() {
  vec2 uv = vUv;
  vec4 base = texture(uTex, uv);
  vec3 col = base.rgb;

  float ny = float(uv.y * 216.0);

  if (uChromaLuma || uChromaLag) {
    vec3 yiq = rgbToYiq(col);
    float y = yiq.r;
    float i = yiq.g;
    float q = yiq.b;

    if (uChromaLuma) {
      float yBlur = uChromaBlurI * 0.1;
      float cBlur = uChromaBlurI;

      float samples = 0.0;
      float iSum = 0.0;
      float qSum = 0.0;
      for (float x = -cBlur; x <= cBlur; x += 1.0) {
        vec3 sampleYiq = rgbToYiq(texture(uTex, uv + vec2(x * uTexelSize.x, 0.0)).rgb);
        iSum += sampleYiq.g;
        qSum += sampleYiq.b;
        samples += 1.0;
      }
      i = iSum / samples;
      q = qSum / samples;

      float ySamples = 0.0;
      float ySum = 0.0;
      for (float x = -yBlur; x <= yBlur; x += 1.0) {
        vec3 sampleYiq = rgbToYiq(texture(uTex, uv + vec2(x * uTexelSize.x, 0.0)).rgb);
        ySum += sampleYiq.r;
        ySamples += 1.0;
      }
      y = ySum / ySamples;
    }

    if (uChromaLag) {
      float lagPixels = uChromaLagAmount;
      vec2 lagUv = uv + vec2(lagPixels * uTexelSize.x, 0.0);
      vec3 lagYiq = rgbToYiq(texture(uTex, lagUv).rgb);
      i = mix(i, lagYiq.g, 0.7);
      q = mix(q, lagYiq.b, 0.3);
    }

    yiq = vec3(y, i, q);
    col = yiqToRgb(yiq);
  }

  if (uTapeNoise) {
    vec2 noiseCoord = gl_FragCoord.xy + uNoiseOff;
    float noise = texture(uNoise, fract(noiseCoord / 64.0)).r;
    noise = noise * 2.0 - 1.0;
    float lum = dot(col, vec3(0.299, 0.587, 0.114));
    float noiseBias = (1.0 - lum) * uNoiseScale * 0.3;
    col += vec3(noise * noiseBias);
  }

  float scanline = floor(ny);

  if (uHeadSwitch) {
    float headSwitchStart = 214.0;
    if (ny >= headSwitchStart) {
      float headDist = ny - headSwitchStart;
      if (headDist < uHeadSwitchHeight) {
        float jitter = smoothHash(vec2(scanline + uTime * 3.0, 0.5)) - 0.5;
        float offset = (jitter * 2.0 - 1.0) * uHeadSwitchJitter;
        vec2 shiftedUv = uv + vec2(offset * uTexelSize.x, 0.0);
        col = texture(uTex, shiftedUv).rgb;
        col *= (1.0 - headDist / uHeadSwitchHeight) * 0.9 + 0.1;
      }
    }
  }

  if (uTracking) {
    float jitterNoise = smoothHash(vec2(scanline, uTime * uJitterFreq)) - 0.5;
    float jitterOffset = jitterNoise * uJitterAmount;

    float bandNoise = smoothHash(vec2(uTime * 0.5, floor(ny / 16.0)));
    if (bandNoise > 0.85) {
      float bandPhase = fract(uTime * 0.3);
      jitterOffset += (bandPhase * 2.0 - 1.0) * uJitterAmount * 2.0;
    }

    vec2 jitteredUv = uv + vec2(jitterOffset * uTexelSize.x, 0.0);
    col = texture(uTex, jitteredUv).rgb;
  }

  if (uDropouts) {
    float dropoutChance = hash(vec2(floor(ny / 4.0), floor(uTime * 10.0)));
    if (dropoutChance < uDropoutRate) {
      float dropoutPhase = fract(uTime * 200.0);
      if (dropoutPhase < 0.05 + hash(vec2(ny, uTime)) * 0.1) {
        col = vec3(1.0);
      }
    }
  }

  if (uGhosting && uHasGhost) {
    vec2 ghostUv = uv + vec2(uGhostOffset * uTexelSize.x, 0.0);
    vec3 ghost = texture(uGhostTarget, ghostUv).rgb;
    col = mix(col, ghost, uGhostAmount);
  }

  oColor = vec4(col, base.a);
}
''';

const String ssaoFragSrc = '''
#version 300 es
precision highp float;
in vec2 vUv;
uniform sampler2D uDepth;
uniform vec2 uDepthSize;
uniform float uRadius;
uniform float uBias;
out vec4 oColor;

vec3 reconstructPos(vec2 uv, float depth) {
  vec2 ndc = uv * 2.0 - 1.0;
  return vec3(ndc, depth);
}

float linearDepth(float z) {
  return z;
}

vec3 reconstructNormal(vec2 uv, float depth) {
  vec2 texel = 1.0 / uDepthSize;

  float c = depth;
  float r = texture(uDepth, uv + vec2(texel.x, 0.0)).r;
  float u = texture(uDepth, uv + vec2(0.0, texel.y)).r;

  float ddx = r - c;
  float ddy = u - c;

  vec3 normal = normalize(vec3(-ddx * uDepthSize.x, -ddy * uDepthSize.y, 1.0));
  return normal;
}

void main() {
  float depth = texture(uDepth, vUv).r;

  if (depth >= 1.0) {
    oColor = vec4(1.0);
    return;
  }

  vec3 normal = reconstructNormal(vUv, depth);
  vec2 texel = 1.0 / uDepthSize;

  float occlusion = 0.0;
  float sampleRadius = uRadius * texel.x;

  const float angles[8] = float[](
    0.0,
    0.785398,
    1.570796,
    2.356194,
    3.141593,
    3.926991,
    4.712389,
    5.497787
  );

  for (int i = 0; i < 8; i++) {
    float angle = angles[i];
    vec2 offset = vec2(cos(angle), sin(angle)) * sampleRadius;
    vec2 sampleUv = vUv + offset;

    float sampleDepth = texture(uDepth, sampleUv).r;
    float depthDiff = depth - sampleDepth;

    if (depthDiff > uBias && depthDiff < sampleRadius * 100.0) {
      occlusion += 1.0;
    }
  }

  float ao = 1.0 - (occlusion / 8.0);
  oColor = vec4(vec3(ao), 1.0);
}
''';
