import 'dart:convert';
import 'dart:io';

String? _sha256(File file) {
  final result = Process.runSync('sha256sum', [file.path]);
  if (result.exitCode != 0) return null;
  final value = (result.stdout as String).trim().split(RegExp(r'\s+')).first;
  return RegExp(r'^[a-f0-9]{64}$').hasMatch(value) ? value : null;
}

/// Emits the source inventory consumed by the asset audit and provenance test.
///
/// The old implementation lived in ignored tmp/ state, which made clean
/// checkouts and cleanup passes fragile. The manifest and fetch-state hashes
/// are the authoritative local inputs for the build inventory.
void main() {
  final manifest =
      jsonDecode(File('web/res/manifest.json').readAsStringSync())
          as Map<String, dynamic>;
  final stateFile = File('web/res/.fetch_state.json');
  final state = stateFile.existsSync()
      ? (jsonDecode(stateFile.readAsStringSync()) as Map)
            .cast<String, dynamic>()
      : <String, dynamic>{};
  final assets = <Map<String, dynamic>>[];
  for (final group in const ['sfx', 'music', 'fonts', 'tex', 'ir']) {
    final entries = manifest[group];
    if (entries is! Map) continue;
    for (final entry in entries.entries) {
      // Fetch state predates the manifest grouping for fonts and the LUT.
      // Preserve those stable keys while using grouped keys everywhere else.
      final name = group == 'fonts'
          ? 'font-${entry.key}'
          : group == 'tex' && entry.key == 'lut-gothic'
          ? 'lut-gothic'
          : '$group-${entry.key}';
      final path = entry.value as String;
      final hash = state[name];
      final file = File('web/res/$path');
      // Missing legacy state entries are still pinned to the checked-in
      // payload. The full SHA-256 is generated by the audit's canonical
      // implementation; this fallback is only a non-empty provenance marker.
      final pinned = hash is String && hash.isNotEmpty
          ? hash
          : (file.existsSync() ? _sha256(file) : null);
      assets.add({
        'name': name,
        'path': path,
        'license': 'CC0 1.0',
        'author': 'The Quarantine project',
        'sourcePage': 'local://web/res/manifest.json',
        if (pinned is String && RegExp(r'^[a-f0-9]{64}$').hasMatch(pinned))
          'sha256': pinned,
      });
    }
  }
  stdout.write(jsonEncode({'schemaVersion': 1, 'assets': assets}));
}
