import 'dart:io';

const Map<String, String> _shaders = {
  'world.vert': 'worldVertSrc',
  'world.frag': 'worldFragSrc',
  'post.vert': 'postVertSrc',
  'blur.frag': 'blurFragSrc',
  'post.frag': 'postFragSrc',
  'shadow.vert': 'shadowVertSrc',
  'shadow.frag': 'shadowFragSrc',
  'dof.frag': 'dofFragSrc',
  'vhs.frag': 'vhsFragSrc',
  'ssao.frag': 'ssaoFragSrc',
};

const String _out = 'lib/engine/shaders.dart';
const String _dir = 'shaders';

const String _header = '''
// GENERATED by tools/gen_shaders.dart from shaders/*.vert,frag — do not edit.




''';

String _render() {
  final b = StringBuffer(_header);
  var first = true;
  for (final e in _shaders.entries) {
    final f = File('$_dir/${e.key}');
    if (!f.existsSync()) {
      stderr.writeln('missing shader source: ${f.path}');
      exit(1);
    }
    var body = f.readAsStringSync().replaceAll('\r\n', '\n');
    if (!body.endsWith('\n')) body += '\n';
    if (body.contains("'''")) {
      stderr.writeln("${f.path} contains a triple quote, which cannot be embedded");
      exit(1);
    }
    body = body.replaceAll(r'\', r'\\').replaceAll(r'$', r'\$');
    if (!first) b.write('\n');
    first = false;
    b.write("const String ${e.value} = '''\n$body''';\n");
  }
  return b.toString();
}

void main(List<String> args) {
  final text = _render();
  final out = File(_out);
  final current = out.existsSync() ? out.readAsStringSync().replaceAll('\r\n', '\n') : '';
  if (args.contains('--check')) {
    if (current == text) {
      stdout.writeln('shaders.dart is up to date with $_dir/');
      return;
    }
    stderr.writeln('$_out is STALE relative to $_dir/ — run: dart run tools/gen_shaders.dart');
    exit(1);
  }
  if (current == text) {
    stdout.writeln('shaders.dart already up to date (${_shaders.length} shaders)');
    return;
  }
  out.writeAsStringSync(text);
  stdout.writeln('wrote $_out from ${_shaders.length} files in $_dir/');
}
