#!/usr/bin/env python3
"""Small Tkinter editor for text/story.screenplay.

The editor intentionally uses only Python's standard library. The screenplay
file remains the source of truth; this is a friendly editor for the same
line-oriented format used by tools/story_build.dart, not a second story format.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
try:
    import tkinter as tk
    from tkinter import messagebox, ttk
except ImportError:  # Allows --help and clear diagnostics on headless builders.
    tk = None  # type: ignore[assignment]
    messagebox = None  # type: ignore[assignment]
    ttk = None  # type: ignore[assignment]


@dataclass
class Beat:
    kind: str
    text: str
    speaker: str | None = None


@dataclass
class Option:
    option_id: str
    next_scene: str
    label: str


@dataclass
class Branch:
    branch_id: str
    prompt: str
    options: list[Option] = field(default_factory=list)


@dataclass
class Scene:
    scene_id: str
    day: int
    title: str
    links: list[str] = field(default_factory=list)
    beats: list[Beat] = field(default_factory=list)
    branches: list[Branch] = field(default_factory=list)


@dataclass
class Script:
    sources: list[str] = field(default_factory=list)
    scenes: list[Scene] = field(default_factory=list)


def parse_script(path: Path) -> Script:
    script = Script()
    scene: Scene | None = None
    branch: Branch | None = None

    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        head, _, value = line.partition("|")
        words = head.strip().split()
        if not words:
            continue
        record = words[0]
        value = value.strip()
        try:
            if record == "SOURCE":
                script.sources.append(words[1])
            elif record == "SCENE":
                if len(words) < 4:
                    raise ValueError("SCENE needs id, day, and title")
                scene = Scene(words[1], int(words[2]), " ".join(words[3:]))
                script.scenes.append(scene)
                branch = None
            elif record == "LINK":
                _need(scene, "LINK")
                scene.links.append(words[1])
            elif record == "BEAT":
                _need(scene, "BEAT")
                scene.beats.append(Beat(words[1], value))
            elif record == "DIALOGUE":
                _need(scene, "DIALOGUE")
                scene.beats.append(Beat("dialogue", value, words[1]))
            elif record == "BRANCH":
                _need(scene, "BRANCH")
                branch = Branch(words[1], value)
                scene.branches.append(branch)
            elif record == "OPTION":
                _need(branch, "OPTION")
                branch.options.append(Option(words[1], words[2], value))
            else:
                raise ValueError(f"unknown record {record}")
        except (IndexError, ValueError) as error:
            raise ValueError(f"{path}:{line_number}: {error}") from error
    return script


def _need(value: object | None, record: str) -> None:
    if value is None:
        raise ValueError(f"{record} appears before its parent")


def encode_script(script: Script) -> str:
    lines = [
        "# THE QUARANTINE — master screenplay",
        "# Generated by tools/screenplay_editor.py. Keep prose in the linked text/*.txt corpus.",
        "",
    ]
    lines.extend(f"SOURCE {source}" for source in script.sources)
    lines.append("")
    for scene in script.scenes:
        lines.append(f"SCENE {scene.scene_id} {scene.day} {scene.title}")
        lines.extend(f"LINK {link}" for link in scene.links)
        for beat in scene.beats:
            if beat.speaker:
                lines.append(f"DIALOGUE {beat.speaker} | {beat.text}")
            else:
                lines.append(f"BEAT {beat.kind} | {beat.text}")
        for branch in scene.branches:
            lines.append(f"BRANCH {branch.branch_id} | {branch.prompt}")
            for option in branch.options:
                lines.append(
                    f"OPTION {option.option_id} {option.next_scene} | {option.label}"
                )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


class Editor(tk.Tk if tk is not None else object):
    def __init__(self, path: Path, no_build: bool = False) -> None:
        super().__init__()
        self.path = path
        self.no_build = no_build
        self.script = parse_script(path)
        self.scene: Scene | None = None
        self.scene_index: int | None = None
        self.branch: Branch | None = None
        self.option: Option | None = None
        self.dirty = False

        self.title("The Quarantine — Screenplay Editor")
        self.geometry("1180x760")
        self.minsize(900, 600)
        self.protocol("WM_DELETE_WINDOW", self.close)
        self.bind("<Control-s>", lambda _event: self.save())
        self._make_widgets()
        self._load_scene(0)

    def _make_widgets(self) -> None:
        self.columnconfigure(1, weight=1)
        self.columnconfigure(2, weight=1)
        self.rowconfigure(0, weight=1)

        left = ttk.Frame(self, padding=8)
        left.grid(row=0, column=0, sticky="ns")
        ttk.Label(left, text="Scenes").pack(anchor="w")
        self.scene_list = tk.Listbox(left, width=28, exportselection=False)
        self.scene_list.pack(fill="y", expand=True)
        for scene in self.script.scenes:
            self.scene_list.insert("end", self._scene_choice_label(scene))
        self.scene_list.bind("<<ListboxSelect>>", self._scene_selected)

        center = ttk.Frame(self, padding=8)
        center.grid(row=0, column=1, sticky="nsew")
        center.columnconfigure(0, weight=1)
        center.rowconfigure(4, weight=1)
        center.rowconfigure(8, weight=1)
        ttk.Label(center, text="Scene").grid(row=0, column=0, sticky="w")
        self.title_var = tk.StringVar()
        ttk.Entry(center, textvariable=self.title_var).grid(row=1, column=0, sticky="ew")
        ttk.Label(center, text="Story moments").grid(
            row=2, column=0, sticky="w", pady=(12, 2)
        )
        self.beat_list = tk.Listbox(center, height=7, exportselection=False)
        self.beat_list.grid(row=4, column=0, sticky="nsew")
        self.beat_list.bind("<<ListboxSelect>>", self._beat_selected)
        beat_form = ttk.LabelFrame(center, text="Selected moment", padding=6)
        beat_form.grid(row=5, column=0, sticky="ew", pady=6)
        beat_form.columnconfigure(1, weight=1)
        self.beat_kind = ttk.Combobox(beat_form, values=("action", "dialogue"), state="readonly", width=12)
        self.beat_kind.grid(row=0, column=1, sticky="w")
        ttk.Label(beat_form, text="Type").grid(row=0, column=0, sticky="w")
        self.beat_speaker_var = tk.StringVar()
        ttk.Label(beat_form, text="Speaker").grid(row=1, column=0, sticky="w")
        ttk.Entry(beat_form, textvariable=self.beat_speaker_var).grid(row=1, column=1, sticky="ew")
        self.beat_text = tk.Text(beat_form, height=5, wrap="word", undo=True)
        self.beat_text.grid(row=2, column=0, columnspan=2, sticky="ew", pady=4)
        beat_buttons = ttk.Frame(beat_form)
        beat_buttons.grid(row=3, column=0, columnspan=2, sticky="e")
        ttk.Button(beat_buttons, text="New moment", command=self._new_beat).pack(side="left", padx=2)
        ttk.Button(beat_buttons, text="Save moment", command=self._save_beat).pack(side="left", padx=2)
        ttk.Button(beat_buttons, text="Remove moment", command=self._remove_beat).pack(side="left", padx=2)
        ttk.Button(center, text="Save scene title", command=self._apply_scene).grid(
            row=6, column=0, sticky="e", pady=2
        )

        right = ttk.Frame(self, padding=8)
        right.grid(row=0, column=2, sticky="nsew")
        right.columnconfigure(0, weight=1)
        right.rowconfigure(4, weight=1)
        ttk.Label(right, text="Choices in this scene").grid(row=0, column=0, sticky="w")
        self.branch_list = ttk.Combobox(right, state="readonly")
        self.branch_list.grid(row=1, column=0, sticky="ew")
        self.branch_list.bind("<<ComboboxSelected>>", self._branch_selected)
        self.prompt_var = tk.StringVar()
        prompt_frame = ttk.LabelFrame(right, text="Question for the player", padding=6)
        prompt_frame.grid(row=2, column=0, sticky="ew", pady=6)
        prompt_frame.columnconfigure(0, weight=1)
        ttk.Entry(prompt_frame, textvariable=self.prompt_var).grid(row=0, column=0, sticky="ew")
        self.option_list = tk.Listbox(right, height=8, exportselection=False)
        self.option_list.grid(row=4, column=0, sticky="nsew")
        self.option_list.bind("<<ListboxSelect>>", self._option_selected)
        option_frame = ttk.LabelFrame(right, text="Selected answer", padding=6)
        option_frame.grid(row=5, column=0, sticky="ew", pady=6)
        option_frame.columnconfigure(1, weight=1)
        self.option_id_var = tk.StringVar()
        self.option_label_var = tk.StringVar()
        ttk.Label(option_frame, text="Answer").grid(row=0, column=0, sticky="w")
        ttk.Entry(option_frame, textvariable=self.option_label_var).grid(row=0, column=1, sticky="ew")
        ttk.Label(option_frame, text="Continue at").grid(row=1, column=0, sticky="w")
        self.next_scene_box = ttk.Combobox(option_frame, state="readonly")
        self.next_scene_box.grid(row=1, column=1, sticky="ew")
        self.next_scene_box["values"] = ["END"] + [self._scene_choice_label(scene) for scene in self.script.scenes]
        option_buttons = ttk.Frame(option_frame)
        option_buttons.grid(row=2, column=0, columnspan=2, sticky="e", pady=(4, 0))
        ttk.Button(option_buttons, text="New answer", command=self._new_option).pack(side="left", padx=2)
        ttk.Button(option_buttons, text="Save answer", command=self._save_option).pack(side="left", padx=2)
        ttk.Button(option_buttons, text="Remove answer", command=self._remove_option).pack(side="left", padx=2)
        ttk.Button(right, text="What am I editing?", command=self._help).grid(row=6, column=0, sticky="e")

        bottom = ttk.Frame(self, padding=(8, 0, 8, 8))
        bottom.grid(row=1, column=0, columnspan=3, sticky="ew")
        bottom.columnconfigure(0, weight=1)
        self.status = ttk.Label(bottom, text=str(self.path))
        self.status.grid(row=0, column=0, sticky="w")
        ttk.Button(bottom, text="Preview scene", command=self._preview).grid(row=0, column=1, padx=4)
        ttk.Button(bottom, text="Save + validate", command=self.save).grid(row=0, column=2, padx=4)
        ttk.Button(bottom, text="Restore last save", command=self._restore_backup).grid(row=0, column=3, padx=4)
        ttk.Button(bottom, text="Quit", command=self.close).grid(row=0, column=4)

    def _scene_selected(self, _event: object = None) -> None:
        selection = self.scene_list.curselection()
        if selection and selection[0] != self.scene_index:
            self._load_scene(selection[0])

    def _mark_dirty(self) -> None:
        self.dirty = True
        self.title(f"The Quarantine — Screenplay Editor • unsaved changes")

    def _load_scene(self, index: int) -> None:
        if not self.script.scenes or index < 0 or index >= len(self.script.scenes):
            return
        self._apply_branch()
        self._apply_scene()
        self.scene_index = index
        self.scene = self.script.scenes[index]
        self.scene_list.selection_clear(0, "end")
        self.scene_list.selection_set(index)
        self.title_var.set(self.scene.title)
        self.beat_list.delete(0, "end")
        for beat in self.scene.beats:
            self.beat_list.insert("end", self._beat_label(beat))
        if self.scene.beats:
            self.beat_list.selection_set(0)
            self._load_beat(0)
        else:
            self._load_beat(None)
        self.branch_list["values"] = [
            f"Choice {number + 1} — {branch.prompt[:52]}"
            for number, branch in enumerate(self.scene.branches)
        ]
        if self.scene.branches:
            self.branch_list.current(0)
            self._load_branch(0)
        else:
            self.branch_list.set("")
            self._load_branch(None)

    def _apply_scene(self) -> None:
        if self.scene is None:
            return
        new_title = self.title_var.get().strip() or self.scene.title
        changed = new_title != self.scene.title
        self.scene.title = new_title
        if changed and self.scene_index is not None:
            self.scene_list.itemconfigure(
                self.scene_index, text=self._scene_choice_label(self.scene)
            )
        # Loading a different scene also synchronizes the old scene. If that
        # synchronization discovers a real edit, it must remain recoverable;
        # only a no-op load is clean.
        if changed:
            self._mark_dirty()

    @staticmethod
    def _beat_label(beat: Beat) -> str:
        who = f"{beat.speaker}: " if beat.speaker else ""
        return f"{beat.kind.title()} — {who}{beat.text[:70]}"

    def _beat_selected(self, _event: object = None) -> None:
        selection = self.beat_list.curselection()
        self._load_beat(selection[0] if selection else None)

    def _load_beat(self, index: int | None) -> None:
        self.beat_kind.set("")
        self.beat_speaker_var.set("")
        self.beat_text.delete("1.0", "end")
        if self.scene is None or index is None or index >= len(self.scene.beats):
            return
        beat = self.scene.beats[index]
        self.beat_kind.set(beat.kind)
        self.beat_speaker_var.set(beat.speaker or "")
        self.beat_text.insert("1.0", beat.text)

    def _beat_from_form(self) -> Beat | None:
        kind = self.beat_kind.get().strip()
        text = self.beat_text.get("1.0", "end").strip()
        speaker = self.beat_speaker_var.get().strip() or None
        if kind not in ("action", "dialogue") or not text:
            messagebox.showerror("A moment needs words", "Choose Action or Dialogue and write what happens.")
            return None
        if kind == "dialogue" and not speaker:
            messagebox.showerror("Who is speaking?", "Dialogue needs a speaker name.")
            return None
        return Beat(kind, text, speaker if kind == "dialogue" else None)

    def _new_beat(self) -> None:
        self.beat_list.selection_clear(0, "end")
        self._load_beat(None)
        self.beat_kind.set("action")
        self.beat_text.focus_set()

    def _save_beat(self) -> None:
        if self.scene is None:
            return
        beat = self._beat_from_form()
        if beat is None:
            return
        selection = self.beat_list.curselection()
        if selection:
            self.scene.beats[selection[0]] = beat
        else:
            self.scene.beats.append(beat)
        self.beat_list.delete(0, "end")
        for candidate in self.scene.beats:
            self.beat_list.insert("end", self._beat_label(candidate))
        index = selection[0] if selection else len(self.scene.beats) - 1
        self.beat_list.selection_set(index)
        self._load_beat(index)
        self._mark_dirty()

    def _remove_beat(self) -> None:
        if self.scene is None:
            return
        selection = self.beat_list.curselection()
        if not selection:
            return
        if not messagebox.askyesno("Remove moment?", "Remove this story moment?"):
            return
        del self.scene.beats[selection[0]]
        self._load_scene(self.script.scenes.index(self.scene))
        self._mark_dirty()

    def _branch_selected(self, _event: object = None) -> None:
        index = self.branch_list.current()
        self._apply_branch()
        self._load_branch(index if index >= 0 else None)

    def _load_branch(self, index: int | None) -> None:
        self.branch = None
        self.option = None
        self.prompt_var.set("")
        self.option_list.delete(0, "end")
        self.option_id_var.set("")
        self.next_scene_box.set("")
        self.option_label_var.set("")
        if self.scene is None or index is None or index >= len(self.scene.branches):
            return
        self.branch = self.scene.branches[index]
        self.prompt_var.set(self.branch.prompt)
        for option in self.branch.options:
            self.option_list.insert("end", self._option_label(option))
        if self.branch.options:
            self.option_list.selection_set(0)
            self._load_option(0)

    def _apply_branch(self) -> None:
        if self.branch is None:
            return
        new_prompt = self.prompt_var.get().strip() or self.branch.prompt
        changed = new_prompt != self.branch.prompt
        self.branch.prompt = new_prompt
        if changed and self.scene is not None:
            branch_values = [
                f"Choice {number + 1} — {candidate.prompt[:52]}"
                for number, candidate in enumerate(self.scene.branches)
            ]
            selected = self.branch_list.current()
            self.branch_list["values"] = branch_values
            if selected >= 0:
                self.branch_list.current(selected)
        if changed:
            self._mark_dirty()

    @staticmethod
    def _option_label(option: Option) -> str:
        return f"{option.label[:58]}  →  {option.next_scene}"

    def _option_selected(self, _event: object = None) -> None:
        selection = self.option_list.curselection()
        self._load_option(selection[0] if selection else None)

    def _load_option(self, index: int | None) -> None:
        self.option = None
        self.option_id_var.set("")
        self.next_scene_box.set("")
        self.option_label_var.set("")
        if self.branch is None or index is None or index >= len(self.branch.options):
            return
        self.option = self.branch.options[index]
        self.option_id_var.set(self.option.option_id)
        self.next_scene_box.set(self._scene_choice_label_for_id(self.option.next_scene))
        self.option_label_var.set(self.option.label)

    @staticmethod
    def _scene_choice_label(scene: Scene) -> str:
        return f"Day {scene.day:02d} — {scene.title}"

    def _scene_choice_label_for_id(self, scene_id: str) -> str:
        if scene_id == "END":
            return "END"
        for scene in self.script.scenes:
            if scene.scene_id == scene_id:
                return self._scene_choice_label(scene)
        return scene_id

    def _scene_id_from_choice(self) -> str:
        choice = self.next_scene_box.get().strip()
        if choice == "END":
            return choice
        for scene in self.script.scenes:
            if choice == self._scene_choice_label(scene):
                return scene.scene_id
        return choice

    def _option_from_form(self) -> Option | None:
        next_scene = self._scene_id_from_choice()
        label = self.option_label_var.get().strip()
        if not next_scene or not label:
            messagebox.showerror("An answer needs words", "Write the answer and choose where the story continues.")
            return None
        option_id = self.option_id_var.get().strip() or self._new_internal_label(label)
        return Option(option_id, next_scene, label)

    def _new_internal_label(self, label: str) -> str:
        stem = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-") or "answer"
        candidate = f"choice-{stem}"
        existing = {
            option.option_id
            for scene in self.script.scenes
            for branch in scene.branches
            for option in branch.options
        }
        number = 2
        while candidate in existing:
            candidate = f"choice-{stem}-{number}"
            number += 1
        return candidate

    def _new_option(self) -> None:
        self.option_list.selection_clear(0, "end")
        self._load_option(None)
        self.option_label_var.set("New answer")
        self.next_scene_box.set("END")

    def _save_option(self) -> None:
        if self.branch is None:
            return
        option = self._option_from_form()
        if option is None:
            return
        selection = self.option_list.curselection()
        if selection:
            self.branch.options[selection[0]] = option
        else:
            self.branch.options.append(option)
        self._load_branch(self.scene.branches.index(self.branch))
        self.option_list.selection_set(selection[0] if selection else len(self.branch.options) - 1)
        self._load_option(self.option_list.curselection()[0])
        self._mark_dirty()

    def _remove_option(self) -> None:
        if self.branch is None:
            return
        selection = self.option_list.curselection()
        if not selection:
            return
        if not messagebox.askyesno("Remove answer?", "Remove this answer from the choice?"):
            return
        del self.branch.options[selection[0]]
        self._load_branch(self.scene.branches.index(self.branch))
        self._mark_dirty()

    def _preview(self) -> None:
        if self.scene is None:
            return
        preview = tk.Toplevel(self)
        preview.title(f"Preview — Day {self.scene.day:02d}: {self.scene.title}")
        preview.geometry("620x560")
        preview.columnconfigure(0, weight=1)
        preview.rowconfigure(0, weight=1)
        text = tk.Text(preview, wrap="word", padx=18, pady=18)
        text.grid(row=0, column=0, sticky="nsew")
        text.insert("end", f"DAY {self.scene.day}\n{self.scene.title}\n\n")
        for beat in self.scene.beats:
            if beat.speaker:
                text.insert("end", f"{beat.speaker.upper()}\n{beat.text}\n\n")
            else:
                text.insert("end", f"[{beat.text}]\n\n")
        for branch in self.scene.branches:
            text.insert("end", f"{branch.prompt}\n")
            for option in branch.options:
                text.insert("end", f"  • {option.label}\n")
            text.insert("end", "\n")
        text.configure(state="disabled")

    def _restore_backup(self) -> None:
        backup = self.path.with_name(self.path.name + ".bak")
        if not backup.exists():
            messagebox.showinfo("No earlier save", "There is no earlier saved version to restore yet.")
            return
        if not messagebox.askyesno(
            "Restore the earlier save?",
            "This will replace the current screenplay with the last saved copy. Continue?",
        ):
            return
        try:
            restored_script = parse_script(backup)
            current_text = self.path.read_text(encoding="utf-8")
            backup_text = backup.read_text(encoding="utf-8")
        except (OSError, ValueError) as error:
            messagebox.showerror(
                "Could not restore",
                f"The earlier copy could not be opened safely:\n\n{error}",
            )
            return
        before_restore = self.path.with_name(self.path.name + ".before-restore.bak")
        try:
            before_restore.write_text(current_text, encoding="utf-8")
            temporary = self.path.with_name(self.path.name + ".restore.tmp")
            temporary.write_text(backup_text, encoding="utf-8")
            temporary.replace(self.path)
        except OSError as error:
            messagebox.showerror("Could not restore", f"Nothing was changed:\n\n{error}")
            return
        self.script = restored_script
        self.scene = None
        self.branch = None
        self.scene_list.delete(0, "end")
        for scene in self.script.scenes:
            self.scene_list.insert("end", self._scene_choice_label(scene))
        self.next_scene_box["values"] = ["END"] + [
            self._scene_choice_label(scene) for scene in self.script.scenes
        ]
        self._load_scene(0)
        self.dirty = False
        self.title("The Quarantine — Screenplay Editor")
        self.status["text"] = f"Restored. The replaced copy is kept at {before_restore.name}."

    def _help(self) -> None:
        messagebox.showinfo(
            "A gentle guide",
            "Scene: one day in the story.\n\n"
            "Story moments: things the player sees or hears. Use Action for description and Dialogue for spoken words.\n\n"
            "Choices: the question shown to the player. Each answer leads to another day, or END for an ending.\n\n"
            "The filing label is hidden; the editor creates one for you.\n\n"
            "Your old screenplay is backed up as story.screenplay.bak whenever you save.",
        )

    def save(self) -> None:
        self._apply_scene()
        self._apply_branch()
        backup = self.path.with_name(self.path.name + ".bak")
        try:
            old_text = self.path.read_text(encoding="utf-8")
            new_text = encode_script(self.script)
            backup.write_text(old_text, encoding="utf-8")
            temporary = self.path.with_name(self.path.name + ".save.tmp")
            temporary.write_text(new_text, encoding="utf-8")
            temporary.replace(self.path)
        except OSError as error:
            messagebox.showerror(
                "Could not save",
                f"Your changes are still open in the editor, but the file was not changed:\n\n{error}",
            )
            return
        self.dirty = False
        self.title("The Quarantine — Screenplay Editor")
        if self.no_build:
            self.status["text"] = f"Saved. A backup is kept at {backup.name}."
            return
        try:
            result = subprocess.run(
                ["dart", "run", "tools/story_build.dart"],
                cwd=self.path.parent.parent,
                text=True,
                capture_output=True,
                check=False,
            )
            if result.returncode:
                self.status["text"] = "Saved, but the story needs attention"
                messagebox.showerror(
                    "A small story problem",
                    "The screenplay was saved safely, but the checker found something to fix:\n\n"
                    + (result.stderr or result.stdout),
                )
            else:
                self.status["text"] = "Saved and checked. A backup is kept beside the screenplay."
        except FileNotFoundError:
            self.status["text"] = "Saved. Dart is unavailable; a backup is kept beside the screenplay."

    def close(self) -> None:
        if self.dirty and not messagebox.askyesno("Unsaved changes", "Discard unsaved changes?"):
            return
        self.destroy()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", default="text/story.screenplay")
    parser.add_argument("--no-build", action="store_true", help="save without running the Dart validator")
    args = parser.parse_args()
    path = Path(args.path).resolve()
    if not path.exists():
        print(f"screenplay not found: {path}", file=sys.stderr)
        return 2
    if tk is None:
        print(
            "Tkinter is unavailable. Install the system Tk package, then rerun "
            "this editor (or use dart run tools/story_build.dart for validation).",
            file=sys.stderr,
        )
        return 3
    try:
        app = Editor(path, args.no_build)
    except (OSError, ValueError) as error:
        print(f"cannot open screenplay: {error}", file=sys.stderr)
        return 2
    app.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
