import 'dart:io';

void main() {
  final smoke = File('tools/browser/renderer_smoke.cjs').readAsStringSync();
  final host = File('web/main.dart').readAsStringSync();
  const smokeFields = [
    'diagnosticGroups',
    'rainParticleRequested',
    'rainParticleBudget',
    'rainParticleFrustumVisible',
    'rainParticleAverageSpeedMps',
    'rainFlowParticles',
    'rainFlowPaths',
    'rainFlowCapturedMassKg',
    'rainFlowDrainedMassKg',
    'rainFlowOverflowMassKg',
    'rainFlowWetness',
    'fireFlameParticles',
    'fireWhiteSmokeParticles',
    'fireBlackSmokeParticles',
    'weatherPhase',
    'weatherWindMps',
    'weatherSnowAccumulationRateMps',
    'weatherImpactEnergyFluxWm2',
    'weatherWarmClearanceM',
    'weatherLocalTemperatureC',
    'weatherCondensationSuppression',
    'weatherImpactCount',
    'weatherSettledMassKg',
    'weatherReboundEnergyJ',
    'weatherObstacleCount',
    'solarPhase',
    'solarSunriseHours',
    'solarSunsetHours',
    'solarElevationDegrees',
    'solarHorizonBlend',
    'solarTransmittance',
    'volumetricSourceCount',
    'volumetricSourceRadiance',
    'volumetricSourceDirection',
    'volumetricMediumScattering',
    'reflectionIntensity',
    'reflectionConfidence',
    'reflectionMode',
    'skyCloudCoverage',
    'skyCloudDensity',
    'skyCloudSamples',
    'skyCloudPhase',
    'weatherSnowCoverage',
    'weatherMaterialDissolution',
    'weatherWaterFilmM',
    'lightningSourceDistanceM',
    'storyJournalEntryCount',
    'endingKind',
    'endingTextureCount',
  ];
  final missingSmoke = [
    for (final field in smokeFields)
      if (!smoke.contains(field)) field,
  ];
  if (missingSmoke.isNotEmpty) {
    throw StateError('capture metadata fields are missing: $missingSmoke');
  }
  for (final marker in [
    'data-renderer-diagnostic-groups',
    'data-renderer-query-rejection',
    'data-renderer-clean-baseline',
    'data-house-inventory-status-counts',
    'data-renderer-shader-lab-document',
    'data-renderer-shader-lab-baseline',
    'data-renderer-shader-lab-clipboard',
    'data-renderer-volumetric-sample-count',
    'data-renderer-volumetric-intensity',
    'data-renderer-volumetric-dust-density',
    'data-renderer-volumetric-anisotropy',
    'data-renderer-debug-attachments',
    'data-renderer-debug-attachments-reason',
    'activeStairId',
    'activeStairProgress',
    'data-renderer-rain-particles-frustum-culled',
    'data-renderer-rain-particles-average-speed-mps',
    'data-renderer-rain-flow-particles',
    'data-renderer-rain-flow-paths',
    'data-renderer-rain-flow-captured-mass-kg',
    'data-renderer-rain-flow-drained-mass-kg',
    'data-renderer-rain-flow-overflow-mass-kg',
    'data-renderer-weather-rain-flow-wetness',
    'data-renderer-fire-flame-particles',
    'data-renderer-fire-white-smoke-particles',
    'data-renderer-fire-black-smoke-particles',
    'data-renderer-weather-phase',
    'data-renderer-weather-wind-mps',
    'data-renderer-weather-snow-accumulation-mps',
    'data-renderer-weather-impact-energy-w-m2',
    'data-renderer-weather-warm-clearance-m',
    'data-renderer-weather-local-temperature-c',
    'data-renderer-weather-condensation-suppression',
    'data-renderer-weather-impact-count',
    'data-renderer-weather-settled-mass-kg',
    'data-renderer-weather-rebound-energy-j',
    'data-renderer-weather-obstacle-count',
    'data-renderer-solar-phase',
    'data-renderer-solar-sunrise-hours',
    'data-renderer-solar-sunset-hours',
    'data-renderer-solar-elevation-deg',
    'data-renderer-solar-horizon-blend',
    'data-renderer-solar-transmittance',
    'data-renderer-volumetric-source-count',
    'data-renderer-volumetric-source-radiance',
    'data-renderer-volumetric-source-direction',
    'data-renderer-volumetric-medium-scattering',
    'data-renderer-reflection-intensity',
    'data-renderer-reflection-confidence',
    'data-renderer-reflection-mode',
    'data-renderer-sky-cloud-coverage',
    'data-renderer-sky-cloud-density',
    'data-renderer-sky-cloud-samples',
    'data-renderer-sky-cloud-phase',
    'data-renderer-weather-snow-coverage',
    'data-renderer-weather-material-dissolution',
    'data-renderer-weather-water-film-m',
    'data-renderer-weather-surface',
    'data-renderer-lightning-source-direction',
    'data-renderer-lightning-distance-attenuation',
    '_publishAutomationPlayerState();',
  ]) {
    if (!host.contains(marker)) {
      throw StateError('host capture marker missing: $marker');
    }
  }
  print(
    'capture metadata contract: shader, atmosphere, debug, solar, journal, and frustum evidence are wired',
  );
}
